# docker-compose.prod.yml

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 80
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik_prod:fastapi_traefik_prod@db:5432/fastapi_traefik_prod
      - GUNICORN_CMD_ARGS="--workers=1"
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.1032649-cu51513.tmweb.ru/`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik_prod
      - POSTGRES_PASSWORD=fastapi_traefik_prod
      - POSTGRES_DB=fastapi_traefik_prod
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile.react
    ports: [3000]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`web.1032649-cu51513.tmweb.ru`)"
      - "traefik.http.routers.react.tls=true"
#      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.routers.react.tls.certresolver=letsencrypt"
      - "traefik.http.routers.react.tls.domains[0].main=web.1032649-cu51513.tmweb.ru"
      - "traefik.http.routers.react.tls.domains[0].sans=www.web.1032649-cu51513.tmweb.ru"
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.1032649-cu51513.tmweb.ru`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=testuser:$$apr1$$vac5P01I$$wfPTdDCNwLLWEY58hsAA60"

volumes:
  postgres_data_prod:
  traefik-public-certificates:
